version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/laravel:/var/www/laravel
    depends_on:
      - php-fpm

  php-fpm:
    image: westside072/php-fpm:8.1.2
    volumes:
      - ./www/laravel:/var/www/laravel
      - ./docker/php-fpm/php.ini:/etc/php/8.1/fpm/php.ini
      - ./docker/php-fpm/php.ini:/etc/php/8.1/cli/php.ini
    working_dir: /var/www/laravel
    ports:
      - 8008:8000
      - 8181:8181
    depends_on:
      - mysqldb

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - mysqldb

  mysqldb:
    image: jamielsharief/mysql:latest
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: petProject
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  mysqldb-test:
    image: jamielsharief/mysql:latest
    container_name: app-mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: petProject
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 8011:3306